micronaut:
  application:
    name: demo
  server:
    port: 5000
    cors:
      enabled: true
test-resources:
  containers:
    mariadb:
      image-name: mariadb:latest
  default:
    dialect: MYSQL
    username: root
    password: test
    db-type: mariadb
    jdbc-url: jdbc:tc:mariadb://localhost/pokemon
    driverClassName: org.testcontainers.jdbc.ContainerDatabaseDriver
datasources:
  default:
    driver-class-name: ${DATASOURCES_DEFAULT_DRIVER:org.mariadb.jdbc.Driver}
    db-type: mariadb
    dialect: MYSQL
    jdbc-url: ${DATASOURCES_DEFAULT_URL:`jdbc:mariadb://localhost:4000/pokemon`}
    username: ${DATASOURCES_DEFAULT_USER:example-user}
    password: ${DATASOURCES_DEFAULT_PASSWORD:my_cool_secret}
netty:
  default:
    allocator:
      max-order: 3
liquibase:
  datasources:
    default:
      change-log: classpath:db/liquibase-changelog.yml
